/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "secondary-fixed-dim": "#44ddc1",
        "on-tertiary-fixed": "#341100",
        "primary-fixed-dim": "#adc7ff",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#0e0200",
        "surface": "#f9f9ff",
        "on-secondary-container": "#007261",
        "surface-tint": "#005bc0",
        "outline-variant": "#c1c6d6",
        "on-secondary-fixed": "#00201a",
        "on-background": "#191c23",
        "surface-container": "#ecedf7",
        "surface-container-low": "#f2f3fd",
        "on-primary": "#ffffff",
        "primary-container": "#1a73e8",
        "on-surface": "#191c23",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ffb691",
        "primary-fixed": "#d8e2ff",
        "secondary-container": "#68fadd",
        "on-tertiary-fixed-variant": "#783100",
        "primary": "#005bbf",
        "surface-variant": "#e0e2ec",
        "outline": "#727785",
        "tertiary-container": "#c55500",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#004493",
        "background": "#f9f9ff",
        "surface-container-highest": "#e0e2ec",
        "surface-container-high": "#e6e8f2",
        "tertiary": "#9e4300",
        "on-surface-variant": "#414754",
        "secondary": "#006b5c",
        "inverse-surface": "#2d3038",
        "surface-bright": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#ffffff",
        "surface-dim": "#d8d9e3",
        "error": "#ba1a1a",
        "secondary-fixed": "#68fadd",
        "on-secondary-fixed-variant": "#005145",
        "tertiary-fixed": "#ffdbcb",
        "inverse-primary": "#adc7ff",
        "on-primary-fixed": "#001a41",
        "inverse-on-surface": "#eff0fa"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "xs": "4px",
        "lg": "24px",
        "xl": "32px",
        "base": "4px",
        "grid-gutter": "24px",
        "grid-columns": "12",
        "md": "16px",
        "sm": "8px",
        "grid-margin": "32px"
      },
      "fontFamily": {
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "h2": ["Manrope"],
        "h3": ["Manrope"],
        "h1": ["Manrope"],
        "label-md": ["Inter"],
        "manrope": ["Manrope", "Inter", "system-ui", "sans-serif"],
        "display": ["Manrope", "Inter", "system-ui", "sans-serif"],
        "sans": ["Inter", "system-ui", "sans-serif"]
      },
      "maxWidth": {
        "xs": "20rem",
        "sm": "24rem",
        "md": "28rem",
        "lg": "32rem",
        "xl": "36rem",
        "2xl": "42rem",
        "3xl": "48rem",
        "4xl": "56rem",
        "5xl": "64rem",
        "6xl": "72rem",
        "7xl": "80rem"
      },
      "boxShadow": {
        "level-1": "0 1px 2px 0 rgba(16, 24, 40, 0.04), 0 1px 3px 0 rgba(16, 24, 40, 0.06)",
        "level-2": "0 4px 8px -2px rgba(16, 24, 40, 0.08), 0 2px 4px -2px rgba(16, 24, 40, 0.06)",
        "level-3": "0 12px 24px -6px rgba(16, 24, 40, 0.12), 0 4px 8px -4px rgba(16, 24, 40, 0.06)",
        "level-4": "0 24px 48px -12px rgba(16, 24, 40, 0.18)",
        "focus-ring": "0 0 0 4px rgba(0, 91, 191, 0.16)"
      },
      "fontSize": {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "h2": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "h3": ["24px", {"lineHeight": "32px", "letterSpacing": "0", "fontWeight": "600"}],
        "h1": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600"}]
      }
    }
  },
  plugins: [],
}
