apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medcore-logging
  namespace: argocd
spec:
  project: medcore-platform
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 2.10.1
    chart: loki-stack
    helm:
      values: |
        loki:
          enabled: true
          isDefault: true
        promtail:
          enabled: true
          # THIS IS THE NEW PART: Telling Promtail where Loki actually lives
          config:
            clients:
              - url: http://medcore-logging-loki.logging.svc.cluster.local:3100/loki/api/v1/push
        grafana:
          enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true