apiVersion: v1
kind: ServiceAccount
metadata:
  name: medcore-backend
  namespace: medcore
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: medcore-frontend
  namespace: medcore
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: medcore-database
  namespace: medcore
automountServiceAccountToken: false
